name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ghostscript
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript
          # Remove Ubuntu's restrictive Ghostscript security policy
          sudo rm -f /etc/ghostscript/cidfmap

      - name: Verify Ghostscript installation
        run: |
          gs --version
          which gs
          # Test if Ghostscript can actually process a PDF
          echo "%PDF-1.4" > /tmp/test.pdf
          echo "1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj" >> /tmp/test.pdf
          echo "2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj" >> /tmp/test.pdf
          echo "3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj" >> /tmp/test.pdf
          echo "xref 0 4" >> /tmp/test.pdf
          echo "trailer<</Size 4/Root 1 0 R>>" >> /tmp/test.pdf
          echo "%%EOF" >> /tmp/test.pdf
          gs -sDEVICE=pdfwrite -o /tmp/test_out.pdf /tmp/test.pdf 2>&1 || echo "Ghostscript test failed"
          ls -la /tmp/test*.pdf

      - name: Sync dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: |
          # Ensure gs is in PATH
          export PATH="/usr/bin:$PATH"
          which gs
          gs --version
          uv run pytest -v

  type-check:
    name: Type checking with mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Sync dependencies
        run: uv sync --all-extras

      - name: Run mypy
        run: uv run mypy gs_batch/

  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build package
        run: uv build

      - name: Check build artifacts
        run: |
          ls -lh dist/
          # Check that at least one wheel and one tarball were created
          [ -n "$(ls -A dist/*.whl 2>/dev/null)" ] || (echo "No .whl files found" && exit 1)
          [ -n "$(ls -A dist/*.tar.gz 2>/dev/null)" ] || (echo "No .tar.gz files found" && exit 1)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/
          retention-days: 7
