name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ghostscript
        run: |
          cd /tmp
          wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10040/gs_10.04.0_amd64_snap.tgz
          gunzip gs_10.04.0_amd64_snap.tgz
          tar xvf gs_10.04.0_amd64_snap.tar
          cd gs_10.04.0_amd64_snap
          sudo snap install --devmode gs_10.04.0_amd64.snap

      - name: Verify Ghostscript installation
        run: |
          /snap/bin/gs --version
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Sync dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: |
          # Add /snap/bin to PATH for this step
          export PATH="/snap/bin:$PATH"
          # Verify gs is accessible
          gs --version
          which gs
          # Run tests with verbose Ghostscript output
          uv run pytest -v -s

  type-check:
    name: Type checking with mypy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Sync dependencies
        run: uv sync --all-extras

      - name: Run mypy
        run: uv run mypy gs_batch/

  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build package
        run: uv build

      - name: Check build artifacts
        run: |
          ls -lh dist/
          # Check that at least one wheel and one tarball were created
          [ -n "$(ls -A dist/*.whl 2>/dev/null)" ] || (echo "No .whl files found" && exit 1)
          [ -n "$(ls -A dist/*.tar.gz 2>/dev/null)" ] || (echo "No .tar.gz files found" && exit 1)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/
          retention-days: 7
